# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.common import common_pb2 as proto_dot_common_dot_common__pb2
from proto.employee import employee_pb2 as proto_dot_employee_dot_employee__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/employee/employee_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmployeeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmployee = channel.unary_unary(
                '/employee.EmployeeService/GetEmployee',
                request_serializer=proto_dot_employee_dot_employee__pb2.GetEmployeeRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.GetEmployeeByNumber = channel.unary_unary(
                '/employee.EmployeeService/GetEmployeeByNumber',
                request_serializer=proto_dot_employee_dot_employee__pb2.GetEmployeeByNumberRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.GetEmployeeByEmail = channel.unary_unary(
                '/employee.EmployeeService/GetEmployeeByEmail',
                request_serializer=proto_dot_employee_dot_employee__pb2.GetEmployeeByEmailRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.ListEmployees = channel.unary_unary(
                '/employee.EmployeeService/ListEmployees',
                request_serializer=proto_dot_employee_dot_employee__pb2.ListEmployeesRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)
        self.CreateEmployee = channel.unary_unary(
                '/employee.EmployeeService/CreateEmployee',
                request_serializer=proto_dot_employee_dot_employee__pb2.CreateEmployeeRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.UpdateEmployee = channel.unary_unary(
                '/employee.EmployeeService/UpdateEmployee',
                request_serializer=proto_dot_employee_dot_employee__pb2.UpdateEmployeeRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.DeleteEmployee = channel.unary_unary(
                '/employee.EmployeeService/DeleteEmployee',
                request_serializer=proto_dot_employee_dot_employee__pb2.DeleteEmployeeRequest.SerializeToString,
                response_deserializer=proto_dot_common_dot_common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetEmployeeSubordinates = channel.unary_unary(
                '/employee.EmployeeService/GetEmployeeSubordinates',
                request_serializer=proto_dot_employee_dot_employee__pb2.GetSubordinatesRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)
        self.GetEmployeesByOrgUnit = channel.unary_unary(
                '/employee.EmployeeService/GetEmployeesByOrgUnit',
                request_serializer=proto_dot_employee_dot_employee__pb2.GetEmployeesByOrgUnitRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)
        self.BatchGetEmployees = channel.unary_unary(
                '/employee.EmployeeService/BatchGetEmployees',
                request_serializer=proto_dot_employee_dot_employee__pb2.BatchGetEmployeesRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)
        self.SoftDeleteEmployee = channel.unary_unary(
                '/employee.EmployeeService/SoftDeleteEmployee',
                request_serializer=proto_dot_employee_dot_employee__pb2.SoftDeleteEmployeeRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.RestoreEmployee = channel.unary_unary(
                '/employee.EmployeeService/RestoreEmployee',
                request_serializer=proto_dot_employee_dot_employee__pb2.RestoreEmployeeRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.ListDeletedEmployees = channel.unary_unary(
                '/employee.EmployeeService/ListDeletedEmployees',
                request_serializer=proto_dot_employee_dot_employee__pb2.ListDeletedEmployeesRequest.SerializeToString,
                response_deserializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)


class EmployeeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeeByNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeeByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeeSubordinates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeesByOrgUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SoftDeleteEmployee(self, request, context):
        """Soft delete operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeletedEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmployeeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployee,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.GetEmployeeRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.Employee.SerializeToString,
            ),
            'GetEmployeeByNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeeByNumber,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.GetEmployeeByNumberRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.Employee.SerializeToString,
            ),
            'GetEmployeeByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeeByEmail,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.GetEmployeeByEmailRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.Employee.SerializeToString,
            ),
            'ListEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmployees,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.ListEmployeesRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.SerializeToString,
            ),
            'CreateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmployee,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.CreateEmployeeRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.Employee.SerializeToString,
            ),
            'UpdateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmployee,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.UpdateEmployeeRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.Employee.SerializeToString,
            ),
            'DeleteEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmployee,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.DeleteEmployeeRequest.FromString,
                    response_serializer=proto_dot_common_dot_common__pb2.StatusResponse.SerializeToString,
            ),
            'GetEmployeeSubordinates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeeSubordinates,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.GetSubordinatesRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.SerializeToString,
            ),
            'GetEmployeesByOrgUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeesByOrgUnit,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.GetEmployeesByOrgUnitRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.SerializeToString,
            ),
            'BatchGetEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetEmployees,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.BatchGetEmployeesRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.SerializeToString,
            ),
            'SoftDeleteEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.SoftDeleteEmployee,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.SoftDeleteEmployeeRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.Employee.SerializeToString,
            ),
            'RestoreEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreEmployee,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.RestoreEmployeeRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.Employee.SerializeToString,
            ),
            'ListDeletedEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeletedEmployees,
                    request_deserializer=proto_dot_employee_dot_employee__pb2.ListDeletedEmployeesRequest.FromString,
                    response_serializer=proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'employee.EmployeeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('employee.EmployeeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmployeeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/GetEmployee',
            proto_dot_employee_dot_employee__pb2.GetEmployeeRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployeeByNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/GetEmployeeByNumber',
            proto_dot_employee_dot_employee__pb2.GetEmployeeByNumberRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployeeByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/GetEmployeeByEmail',
            proto_dot_employee_dot_employee__pb2.GetEmployeeByEmailRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/ListEmployees',
            proto_dot_employee_dot_employee__pb2.ListEmployeesRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/CreateEmployee',
            proto_dot_employee_dot_employee__pb2.CreateEmployeeRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/UpdateEmployee',
            proto_dot_employee_dot_employee__pb2.UpdateEmployeeRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/DeleteEmployee',
            proto_dot_employee_dot_employee__pb2.DeleteEmployeeRequest.SerializeToString,
            proto_dot_common_dot_common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployeeSubordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/GetEmployeeSubordinates',
            proto_dot_employee_dot_employee__pb2.GetSubordinatesRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployeesByOrgUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/GetEmployeesByOrgUnit',
            proto_dot_employee_dot_employee__pb2.GetEmployeesByOrgUnitRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/BatchGetEmployees',
            proto_dot_employee_dot_employee__pb2.BatchGetEmployeesRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SoftDeleteEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/SoftDeleteEmployee',
            proto_dot_employee_dot_employee__pb2.SoftDeleteEmployeeRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/RestoreEmployee',
            proto_dot_employee_dot_employee__pb2.RestoreEmployeeRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeletedEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/ListDeletedEmployees',
            proto_dot_employee_dot_employee__pb2.ListDeletedEmployeesRequest.SerializeToString,
            proto_dot_employee_dot_employee__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
