"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import proto.common.common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Employee(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class EmployeeMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_NUMBER_FIELD_NUMBER: builtins.int
    EMPLOYEE_NAME_FIELD_NUMBER: builtins.int
    EMPLOYEE_EMAIL_FIELD_NUMBER: builtins.int
    EMPLOYEE_PHONE_FIELD_NUMBER: builtins.int
    EMPLOYEE_POSITION_FIELD_NUMBER: builtins.int
    EMPLOYEE_TYPE_FIELD_NUMBER: builtins.int
    EMPLOYEE_GENDER_FIELD_NUMBER: builtins.int
    EMPLOYEE_ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_FIELD_NUMBER: builtins.int
    EMPLOYEE_SUPERVISOR_ID_FIELD_NUMBER: builtins.int
    SUPERVISOR_FIELD_NUMBER: builtins.int
    EMPLOYEE_METADATA_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    UPDATED_BY_FIELD_NUMBER: builtins.int
    DELETED_AT_FIELD_NUMBER: builtins.int
    DELETED_BY_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    employee_number: builtins.str
    employee_name: builtins.str
    employee_email: builtins.str
    employee_phone: builtins.str
    employee_position: builtins.str
    employee_type: builtins.str
    """Valid values: 'on_site', 'hybrid', 'ho' (head office)"""
    employee_gender: builtins.str
    employee_org_unit_id: builtins.int
    employee_supervisor_id: builtins.int
    is_active: builtins.bool
    created_by: builtins.int
    updated_by: builtins.int
    deleted_by: builtins.int
    @property
    def org_unit(self) -> Global___OrgUnitInfo: ...
    @property
    def supervisor(self) -> Global___EmployeeInfo: ...
    @property
    def employee_metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def deleted_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Soft delete fields"""

    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
        employee_number: builtins.str = ...,
        employee_name: builtins.str = ...,
        employee_email: builtins.str = ...,
        employee_phone: builtins.str = ...,
        employee_position: builtins.str = ...,
        employee_type: builtins.str = ...,
        employee_gender: builtins.str = ...,
        employee_org_unit_id: builtins.int = ...,
        org_unit: Global___OrgUnitInfo | None = ...,
        employee_supervisor_id: builtins.int = ...,
        supervisor: Global___EmployeeInfo | None = ...,
        employee_metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        is_active: builtins.bool = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        created_by: builtins.int = ...,
        updated_by: builtins.int = ...,
        deleted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        deleted_by: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_deleted_at", b"_deleted_at", "_deleted_by", b"_deleted_by", "created_at", b"created_at", "deleted_at", b"deleted_at", "deleted_by", b"deleted_by", "org_unit", b"org_unit", "supervisor", b"supervisor", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_deleted_at", b"_deleted_at", "_deleted_by", b"_deleted_by", "created_at", b"created_at", "created_by", b"created_by", "deleted_at", b"deleted_at", "deleted_by", b"deleted_by", "employee_email", b"employee_email", "employee_gender", b"employee_gender", "employee_id", b"employee_id", "employee_metadata", b"employee_metadata", "employee_name", b"employee_name", "employee_number", b"employee_number", "employee_org_unit_id", b"employee_org_unit_id", "employee_phone", b"employee_phone", "employee_position", b"employee_position", "employee_supervisor_id", b"employee_supervisor_id", "employee_type", b"employee_type", "is_active", b"is_active", "org_unit", b"org_unit", "supervisor", b"supervisor", "updated_at", b"updated_at", "updated_by", b"updated_by"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_deleted_at", b"_deleted_at"]) -> typing.Literal["deleted_at"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_deleted_by", b"_deleted_by"]) -> typing.Literal["deleted_by"] | None: ...

Global___Employee: typing_extensions.TypeAlias = Employee

@typing.final
class EmployeeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_NUMBER_FIELD_NUMBER: builtins.int
    EMPLOYEE_NAME_FIELD_NUMBER: builtins.int
    EMPLOYEE_POSITION_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    employee_number: builtins.str
    employee_name: builtins.str
    employee_position: builtins.str
    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
        employee_number: builtins.str = ...,
        employee_name: builtins.str = ...,
        employee_position: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["employee_id", b"employee_id", "employee_name", b"employee_name", "employee_number", b"employee_number", "employee_position", b"employee_position"]) -> None: ...

Global___EmployeeInfo: typing_extensions.TypeAlias = EmployeeInfo

@typing.final
class OrgUnitInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_CODE_FIELD_NUMBER: builtins.int
    ORG_UNIT_NAME_FIELD_NUMBER: builtins.int
    ORG_UNIT_TYPE_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    org_unit_code: builtins.str
    org_unit_name: builtins.str
    org_unit_type: builtins.str
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
        org_unit_code: builtins.str = ...,
        org_unit_name: builtins.str = ...,
        org_unit_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["org_unit_code", b"org_unit_code", "org_unit_id", b"org_unit_id", "org_unit_name", b"org_unit_name", "org_unit_type", b"org_unit_type"]) -> None: ...

Global___OrgUnitInfo: typing_extensions.TypeAlias = OrgUnitInfo

@typing.final
class GetEmployeeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["employee_id", b"employee_id"]) -> None: ...

Global___GetEmployeeRequest: typing_extensions.TypeAlias = GetEmployeeRequest

@typing.final
class GetEmployeeByNumberRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_NUMBER_FIELD_NUMBER: builtins.int
    employee_number: builtins.str
    def __init__(
        self,
        *,
        employee_number: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["employee_number", b"employee_number"]) -> None: ...

Global___GetEmployeeByNumberRequest: typing_extensions.TypeAlias = GetEmployeeByNumberRequest

@typing.final
class GetEmployeeByEmailRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_EMAIL_FIELD_NUMBER: builtins.int
    employee_email: builtins.str
    def __init__(
        self,
        *,
        employee_email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["employee_email", b"employee_email"]) -> None: ...

Global___GetEmployeeByEmailRequest: typing_extensions.TypeAlias = GetEmployeeByEmailRequest

@typing.final
class ListEmployeesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: builtins.int
    EMPLOYEE_ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    SEARCH_FIELD_NUMBER: builtins.int
    INCLUDE_DETAILS_FIELD_NUMBER: builtins.int
    employee_org_unit_id: builtins.int
    is_active: builtins.bool
    search: builtins.str
    include_details: builtins.bool
    @property
    def pagination(self) -> proto.common.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        pagination: proto.common.common_pb2.Pagination | None = ...,
        employee_org_unit_id: builtins.int | None = ...,
        is_active: builtins.bool | None = ...,
        search: builtins.str | None = ...,
        include_details: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_employee_org_unit_id", b"_employee_org_unit_id", "_include_details", b"_include_details", "_is_active", b"_is_active", "_search", b"_search", "employee_org_unit_id", b"employee_org_unit_id", "include_details", b"include_details", "is_active", b"is_active", "pagination", b"pagination", "search", b"search"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_employee_org_unit_id", b"_employee_org_unit_id", "_include_details", b"_include_details", "_is_active", b"_is_active", "_search", b"_search", "employee_org_unit_id", b"employee_org_unit_id", "include_details", b"include_details", "is_active", b"is_active", "pagination", b"pagination", "search", b"search"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_org_unit_id", b"_employee_org_unit_id"]) -> typing.Literal["employee_org_unit_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_include_details", b"_include_details"]) -> typing.Literal["include_details"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_is_active", b"_is_active"]) -> typing.Literal["is_active"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_search", b"_search"]) -> typing.Literal["search"] | None: ...

Global___ListEmployeesRequest: typing_extensions.TypeAlias = ListEmployeesRequest

@typing.final
class ListEmployeesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEES_FIELD_NUMBER: builtins.int
    PAGINATION_INFO_FIELD_NUMBER: builtins.int
    @property
    def employees(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Employee]: ...
    @property
    def pagination_info(self) -> proto.common.common_pb2.PaginationInfo: ...
    def __init__(
        self,
        *,
        employees: collections.abc.Iterable[Global___Employee] | None = ...,
        pagination_info: proto.common.common_pb2.PaginationInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination_info", b"pagination_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["employees", b"employees", "pagination_info", b"pagination_info"]) -> None: ...

Global___ListEmployeesResponse: typing_extensions.TypeAlias = ListEmployeesResponse

@typing.final
class CreateEmployeeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class EmployeeMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    EMPLOYEE_NUMBER_FIELD_NUMBER: builtins.int
    EMPLOYEE_NAME_FIELD_NUMBER: builtins.int
    EMPLOYEE_EMAIL_FIELD_NUMBER: builtins.int
    EMPLOYEE_PHONE_FIELD_NUMBER: builtins.int
    EMPLOYEE_POSITION_FIELD_NUMBER: builtins.int
    EMPLOYEE_TYPE_FIELD_NUMBER: builtins.int
    EMPLOYEE_GENDER_FIELD_NUMBER: builtins.int
    EMPLOYEE_ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_SUPERVISOR_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_METADATA_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    employee_number: builtins.str
    employee_name: builtins.str
    employee_email: builtins.str
    employee_phone: builtins.str
    employee_position: builtins.str
    employee_type: builtins.str
    """Valid values: 'on_site', 'hybrid', 'ho' (head office)"""
    employee_gender: builtins.str
    employee_org_unit_id: builtins.int
    employee_supervisor_id: builtins.int
    created_by: builtins.int
    @property
    def employee_metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        employee_number: builtins.str = ...,
        employee_name: builtins.str = ...,
        employee_email: builtins.str | None = ...,
        employee_phone: builtins.str | None = ...,
        employee_position: builtins.str | None = ...,
        employee_type: builtins.str | None = ...,
        employee_gender: builtins.str | None = ...,
        employee_org_unit_id: builtins.int | None = ...,
        employee_supervisor_id: builtins.int | None = ...,
        employee_metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        created_by: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_employee_email", b"_employee_email", "_employee_gender", b"_employee_gender", "_employee_org_unit_id", b"_employee_org_unit_id", "_employee_phone", b"_employee_phone", "_employee_position", b"_employee_position", "_employee_supervisor_id", b"_employee_supervisor_id", "_employee_type", b"_employee_type", "employee_email", b"employee_email", "employee_gender", b"employee_gender", "employee_org_unit_id", b"employee_org_unit_id", "employee_phone", b"employee_phone", "employee_position", b"employee_position", "employee_supervisor_id", b"employee_supervisor_id", "employee_type", b"employee_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_employee_email", b"_employee_email", "_employee_gender", b"_employee_gender", "_employee_org_unit_id", b"_employee_org_unit_id", "_employee_phone", b"_employee_phone", "_employee_position", b"_employee_position", "_employee_supervisor_id", b"_employee_supervisor_id", "_employee_type", b"_employee_type", "created_by", b"created_by", "employee_email", b"employee_email", "employee_gender", b"employee_gender", "employee_metadata", b"employee_metadata", "employee_name", b"employee_name", "employee_number", b"employee_number", "employee_org_unit_id", b"employee_org_unit_id", "employee_phone", b"employee_phone", "employee_position", b"employee_position", "employee_supervisor_id", b"employee_supervisor_id", "employee_type", b"employee_type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_email", b"_employee_email"]) -> typing.Literal["employee_email"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_gender", b"_employee_gender"]) -> typing.Literal["employee_gender"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_org_unit_id", b"_employee_org_unit_id"]) -> typing.Literal["employee_org_unit_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_phone", b"_employee_phone"]) -> typing.Literal["employee_phone"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_position", b"_employee_position"]) -> typing.Literal["employee_position"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_supervisor_id", b"_employee_supervisor_id"]) -> typing.Literal["employee_supervisor_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_type", b"_employee_type"]) -> typing.Literal["employee_type"] | None: ...

Global___CreateEmployeeRequest: typing_extensions.TypeAlias = CreateEmployeeRequest

@typing.final
class UpdateEmployeeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class EmployeeMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_NAME_FIELD_NUMBER: builtins.int
    EMPLOYEE_EMAIL_FIELD_NUMBER: builtins.int
    EMPLOYEE_PHONE_FIELD_NUMBER: builtins.int
    EMPLOYEE_POSITION_FIELD_NUMBER: builtins.int
    EMPLOYEE_TYPE_FIELD_NUMBER: builtins.int
    EMPLOYEE_GENDER_FIELD_NUMBER: builtins.int
    EMPLOYEE_ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_SUPERVISOR_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_METADATA_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    UPDATED_BY_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    employee_name: builtins.str
    employee_email: builtins.str
    employee_phone: builtins.str
    employee_position: builtins.str
    employee_type: builtins.str
    """Valid values: 'on_site', 'hybrid', 'ho' (head office)"""
    employee_gender: builtins.str
    employee_org_unit_id: builtins.int
    employee_supervisor_id: builtins.int
    is_active: builtins.bool
    updated_by: builtins.int
    @property
    def employee_metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
        employee_name: builtins.str | None = ...,
        employee_email: builtins.str | None = ...,
        employee_phone: builtins.str | None = ...,
        employee_position: builtins.str | None = ...,
        employee_type: builtins.str | None = ...,
        employee_gender: builtins.str | None = ...,
        employee_org_unit_id: builtins.int | None = ...,
        employee_supervisor_id: builtins.int | None = ...,
        employee_metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        is_active: builtins.bool | None = ...,
        updated_by: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_employee_email", b"_employee_email", "_employee_gender", b"_employee_gender", "_employee_name", b"_employee_name", "_employee_org_unit_id", b"_employee_org_unit_id", "_employee_phone", b"_employee_phone", "_employee_position", b"_employee_position", "_employee_supervisor_id", b"_employee_supervisor_id", "_employee_type", b"_employee_type", "_is_active", b"_is_active", "employee_email", b"employee_email", "employee_gender", b"employee_gender", "employee_name", b"employee_name", "employee_org_unit_id", b"employee_org_unit_id", "employee_phone", b"employee_phone", "employee_position", b"employee_position", "employee_supervisor_id", b"employee_supervisor_id", "employee_type", b"employee_type", "is_active", b"is_active"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_employee_email", b"_employee_email", "_employee_gender", b"_employee_gender", "_employee_name", b"_employee_name", "_employee_org_unit_id", b"_employee_org_unit_id", "_employee_phone", b"_employee_phone", "_employee_position", b"_employee_position", "_employee_supervisor_id", b"_employee_supervisor_id", "_employee_type", b"_employee_type", "_is_active", b"_is_active", "employee_email", b"employee_email", "employee_gender", b"employee_gender", "employee_id", b"employee_id", "employee_metadata", b"employee_metadata", "employee_name", b"employee_name", "employee_org_unit_id", b"employee_org_unit_id", "employee_phone", b"employee_phone", "employee_position", b"employee_position", "employee_supervisor_id", b"employee_supervisor_id", "employee_type", b"employee_type", "is_active", b"is_active", "updated_by", b"updated_by"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_email", b"_employee_email"]) -> typing.Literal["employee_email"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_gender", b"_employee_gender"]) -> typing.Literal["employee_gender"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_name", b"_employee_name"]) -> typing.Literal["employee_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_org_unit_id", b"_employee_org_unit_id"]) -> typing.Literal["employee_org_unit_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_phone", b"_employee_phone"]) -> typing.Literal["employee_phone"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_position", b"_employee_position"]) -> typing.Literal["employee_position"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_supervisor_id", b"_employee_supervisor_id"]) -> typing.Literal["employee_supervisor_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_employee_type", b"_employee_type"]) -> typing.Literal["employee_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_is_active", b"_is_active"]) -> typing.Literal["is_active"] | None: ...

Global___UpdateEmployeeRequest: typing_extensions.TypeAlias = UpdateEmployeeRequest

@typing.final
class DeleteEmployeeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    SOFT_DELETE_FIELD_NUMBER: builtins.int
    DELETED_BY_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    soft_delete: builtins.bool
    deleted_by: builtins.int
    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
        soft_delete: builtins.bool = ...,
        deleted_by: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deleted_by", b"deleted_by", "employee_id", b"employee_id", "soft_delete", b"soft_delete"]) -> None: ...

Global___DeleteEmployeeRequest: typing_extensions.TypeAlias = DeleteEmployeeRequest

@typing.final
class GetSubordinatesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_SUPERVISOR_ID_FIELD_NUMBER: builtins.int
    RECURSIVE_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    employee_supervisor_id: builtins.int
    recursive: builtins.bool
    @property
    def pagination(self) -> proto.common.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        employee_supervisor_id: builtins.int = ...,
        recursive: builtins.bool = ...,
        pagination: proto.common.common_pb2.Pagination | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["employee_supervisor_id", b"employee_supervisor_id", "pagination", b"pagination", "recursive", b"recursive"]) -> None: ...

Global___GetSubordinatesRequest: typing_extensions.TypeAlias = GetSubordinatesRequest

@typing.final
class GetEmployeesByOrgUnitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    INCLUDE_CHILDREN_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    employee_org_unit_id: builtins.int
    include_children: builtins.bool
    @property
    def pagination(self) -> proto.common.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        employee_org_unit_id: builtins.int = ...,
        include_children: builtins.bool = ...,
        pagination: proto.common.common_pb2.Pagination | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["employee_org_unit_id", b"employee_org_unit_id", "include_children", b"include_children", "pagination", b"pagination"]) -> None: ...

Global___GetEmployeesByOrgUnitRequest: typing_extensions.TypeAlias = GetEmployeesByOrgUnitRequest

@typing.final
class BatchGetEmployeesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_IDS_FIELD_NUMBER: builtins.int
    @property
    def employee_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        employee_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["employee_ids", b"employee_ids"]) -> None: ...

Global___BatchGetEmployeesRequest: typing_extensions.TypeAlias = BatchGetEmployeesRequest

@typing.final
class SoftDeleteEmployeeRequest(google.protobuf.message.Message):
    """Soft delete operations messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    DELETED_BY_USER_ID_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    deleted_by_user_id: builtins.int
    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
        deleted_by_user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deleted_by_user_id", b"deleted_by_user_id", "employee_id", b"employee_id"]) -> None: ...

Global___SoftDeleteEmployeeRequest: typing_extensions.TypeAlias = SoftDeleteEmployeeRequest

@typing.final
class RestoreEmployeeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["employee_id", b"employee_id"]) -> None: ...

Global___RestoreEmployeeRequest: typing_extensions.TypeAlias = RestoreEmployeeRequest

@typing.final
class ListDeletedEmployeesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: builtins.int
    SEARCH_FIELD_NUMBER: builtins.int
    search: builtins.str
    @property
    def pagination(self) -> proto.common.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        pagination: proto.common.common_pb2.Pagination | None = ...,
        search: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_search", b"_search", "pagination", b"pagination", "search", b"search"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_search", b"_search", "pagination", b"pagination", "search", b"search"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_search", b"_search"]) -> typing.Literal["search"] | None: ...

Global___ListDeletedEmployeesRequest: typing_extensions.TypeAlias = ListDeletedEmployeesRequest
