"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Pagination(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    page: builtins.int
    limit: builtins.int
    def __init__(
        self,
        *,
        page: builtins.int = ...,
        limit: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "page", b"page"]) -> None: ...

Global___Pagination: typing_extensions.TypeAlias = Pagination

@typing.final
class PaginationInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    TOTAL_ITEMS_FIELD_NUMBER: builtins.int
    TOTAL_PAGES_FIELD_NUMBER: builtins.int
    page: builtins.int
    limit: builtins.int
    total_items: builtins.int
    total_pages: builtins.int
    def __init__(
        self,
        *,
        page: builtins.int = ...,
        limit: builtins.int = ...,
        total_items: builtins.int = ...,
        total_pages: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "page", b"page", "total_items", b"total_items", "total_pages", b"total_pages"]) -> None: ...

Global___PaginationInfo: typing_extensions.TypeAlias = PaginationInfo

@typing.final
class StatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

Global___StatusResponse: typing_extensions.TypeAlias = StatusResponse
