"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import proto.common.common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OrgUnit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class OrgUnitMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_CODE_FIELD_NUMBER: builtins.int
    ORG_UNIT_NAME_FIELD_NUMBER: builtins.int
    ORG_UNIT_TYPE_FIELD_NUMBER: builtins.int
    ORG_UNIT_PARENT_ID_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    ORG_UNIT_LEVEL_FIELD_NUMBER: builtins.int
    ORG_UNIT_PATH_FIELD_NUMBER: builtins.int
    ORG_UNIT_HEAD_ID_FIELD_NUMBER: builtins.int
    HEAD_FIELD_NUMBER: builtins.int
    ORG_UNIT_DESCRIPTION_FIELD_NUMBER: builtins.int
    ORG_UNIT_METADATA_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    UPDATED_BY_FIELD_NUMBER: builtins.int
    EMPLOYEE_COUNT_FIELD_NUMBER: builtins.int
    TOTAL_EMPLOYEE_COUNT_FIELD_NUMBER: builtins.int
    DELETED_AT_FIELD_NUMBER: builtins.int
    DELETED_BY_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    org_unit_code: builtins.str
    org_unit_name: builtins.str
    org_unit_type: builtins.str
    org_unit_parent_id: builtins.int
    org_unit_level: builtins.int
    org_unit_path: builtins.str
    org_unit_head_id: builtins.int
    org_unit_description: builtins.str
    is_active: builtins.bool
    created_by: builtins.int
    updated_by: builtins.int
    employee_count: builtins.int
    total_employee_count: builtins.int
    deleted_by: builtins.int
    @property
    def parent(self) -> Global___OrgUnitInfo: ...
    @property
    def head(self) -> Global___EmployeeInfo: ...
    @property
    def org_unit_metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def deleted_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Soft delete fields"""

    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
        org_unit_code: builtins.str = ...,
        org_unit_name: builtins.str = ...,
        org_unit_type: builtins.str = ...,
        org_unit_parent_id: builtins.int = ...,
        parent: Global___OrgUnitInfo | None = ...,
        org_unit_level: builtins.int = ...,
        org_unit_path: builtins.str = ...,
        org_unit_head_id: builtins.int = ...,
        head: Global___EmployeeInfo | None = ...,
        org_unit_description: builtins.str = ...,
        org_unit_metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        is_active: builtins.bool = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        created_by: builtins.int = ...,
        updated_by: builtins.int = ...,
        employee_count: builtins.int = ...,
        total_employee_count: builtins.int = ...,
        deleted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        deleted_by: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_deleted_at", b"_deleted_at", "_deleted_by", b"_deleted_by", "created_at", b"created_at", "deleted_at", b"deleted_at", "deleted_by", b"deleted_by", "head", b"head", "parent", b"parent", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_deleted_at", b"_deleted_at", "_deleted_by", b"_deleted_by", "created_at", b"created_at", "created_by", b"created_by", "deleted_at", b"deleted_at", "deleted_by", b"deleted_by", "employee_count", b"employee_count", "head", b"head", "is_active", b"is_active", "org_unit_code", b"org_unit_code", "org_unit_description", b"org_unit_description", "org_unit_head_id", b"org_unit_head_id", "org_unit_id", b"org_unit_id", "org_unit_level", b"org_unit_level", "org_unit_metadata", b"org_unit_metadata", "org_unit_name", b"org_unit_name", "org_unit_parent_id", b"org_unit_parent_id", "org_unit_path", b"org_unit_path", "org_unit_type", b"org_unit_type", "parent", b"parent", "total_employee_count", b"total_employee_count", "updated_at", b"updated_at", "updated_by", b"updated_by"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_deleted_at", b"_deleted_at"]) -> typing.Literal["deleted_at"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_deleted_by", b"_deleted_by"]) -> typing.Literal["deleted_by"] | None: ...

Global___OrgUnit: typing_extensions.TypeAlias = OrgUnit

@typing.final
class OrgUnitInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_CODE_FIELD_NUMBER: builtins.int
    ORG_UNIT_NAME_FIELD_NUMBER: builtins.int
    ORG_UNIT_TYPE_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    org_unit_code: builtins.str
    org_unit_name: builtins.str
    org_unit_type: builtins.str
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
        org_unit_code: builtins.str = ...,
        org_unit_name: builtins.str = ...,
        org_unit_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["org_unit_code", b"org_unit_code", "org_unit_id", b"org_unit_id", "org_unit_name", b"org_unit_name", "org_unit_type", b"org_unit_type"]) -> None: ...

Global___OrgUnitInfo: typing_extensions.TypeAlias = OrgUnitInfo

@typing.final
class EmployeeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMPLOYEE_ID_FIELD_NUMBER: builtins.int
    EMPLOYEE_NUMBER_FIELD_NUMBER: builtins.int
    EMPLOYEE_NAME_FIELD_NUMBER: builtins.int
    EMPLOYEE_POSITION_FIELD_NUMBER: builtins.int
    employee_id: builtins.int
    employee_number: builtins.str
    employee_name: builtins.str
    employee_position: builtins.str
    def __init__(
        self,
        *,
        employee_id: builtins.int = ...,
        employee_number: builtins.str = ...,
        employee_name: builtins.str = ...,
        employee_position: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["employee_id", b"employee_id", "employee_name", b"employee_name", "employee_number", b"employee_number", "employee_position", b"employee_position"]) -> None: ...

Global___EmployeeInfo: typing_extensions.TypeAlias = EmployeeInfo

@typing.final
class GetOrgUnitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["org_unit_id", b"org_unit_id"]) -> None: ...

Global___GetOrgUnitRequest: typing_extensions.TypeAlias = GetOrgUnitRequest

@typing.final
class GetOrgUnitByCodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_CODE_FIELD_NUMBER: builtins.int
    org_unit_code: builtins.str
    def __init__(
        self,
        *,
        org_unit_code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["org_unit_code", b"org_unit_code"]) -> None: ...

Global___GetOrgUnitByCodeRequest: typing_extensions.TypeAlias = GetOrgUnitByCodeRequest

@typing.final
class ListOrgUnitsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: builtins.int
    ORG_UNIT_PARENT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_TYPE_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    SEARCH_FIELD_NUMBER: builtins.int
    org_unit_parent_id: builtins.int
    org_unit_type: builtins.str
    is_active: builtins.bool
    search: builtins.str
    @property
    def pagination(self) -> proto.common.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        pagination: proto.common.common_pb2.Pagination | None = ...,
        org_unit_parent_id: builtins.int | None = ...,
        org_unit_type: builtins.str | None = ...,
        is_active: builtins.bool | None = ...,
        search: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_is_active", b"_is_active", "_org_unit_parent_id", b"_org_unit_parent_id", "_org_unit_type", b"_org_unit_type", "_search", b"_search", "is_active", b"is_active", "org_unit_parent_id", b"org_unit_parent_id", "org_unit_type", b"org_unit_type", "pagination", b"pagination", "search", b"search"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_is_active", b"_is_active", "_org_unit_parent_id", b"_org_unit_parent_id", "_org_unit_type", b"_org_unit_type", "_search", b"_search", "is_active", b"is_active", "org_unit_parent_id", b"org_unit_parent_id", "org_unit_type", b"org_unit_type", "pagination", b"pagination", "search", b"search"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_is_active", b"_is_active"]) -> typing.Literal["is_active"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_parent_id", b"_org_unit_parent_id"]) -> typing.Literal["org_unit_parent_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_type", b"_org_unit_type"]) -> typing.Literal["org_unit_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_search", b"_search"]) -> typing.Literal["search"] | None: ...

Global___ListOrgUnitsRequest: typing_extensions.TypeAlias = ListOrgUnitsRequest

@typing.final
class ListOrgUnitsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNITS_FIELD_NUMBER: builtins.int
    PAGINATION_INFO_FIELD_NUMBER: builtins.int
    @property
    def org_units(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___OrgUnit]: ...
    @property
    def pagination_info(self) -> proto.common.common_pb2.PaginationInfo: ...
    def __init__(
        self,
        *,
        org_units: collections.abc.Iterable[Global___OrgUnit] | None = ...,
        pagination_info: proto.common.common_pb2.PaginationInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination_info", b"pagination_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["org_units", b"org_units", "pagination_info", b"pagination_info"]) -> None: ...

Global___ListOrgUnitsResponse: typing_extensions.TypeAlias = ListOrgUnitsResponse

@typing.final
class CreateOrgUnitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class OrgUnitMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ORG_UNIT_CODE_FIELD_NUMBER: builtins.int
    ORG_UNIT_NAME_FIELD_NUMBER: builtins.int
    ORG_UNIT_TYPE_FIELD_NUMBER: builtins.int
    ORG_UNIT_LEVEL_FIELD_NUMBER: builtins.int
    ORG_UNIT_PATH_FIELD_NUMBER: builtins.int
    ORG_UNIT_PARENT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_HEAD_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_DESCRIPTION_FIELD_NUMBER: builtins.int
    ORG_UNIT_METADATA_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    org_unit_code: builtins.str
    org_unit_name: builtins.str
    org_unit_type: builtins.str
    org_unit_level: builtins.int
    org_unit_path: builtins.str
    org_unit_parent_id: builtins.int
    org_unit_head_id: builtins.int
    org_unit_description: builtins.str
    created_by: builtins.int
    @property
    def org_unit_metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        org_unit_code: builtins.str = ...,
        org_unit_name: builtins.str = ...,
        org_unit_type: builtins.str = ...,
        org_unit_level: builtins.int = ...,
        org_unit_path: builtins.str = ...,
        org_unit_parent_id: builtins.int | None = ...,
        org_unit_head_id: builtins.int | None = ...,
        org_unit_description: builtins.str | None = ...,
        org_unit_metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        created_by: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_org_unit_description", b"_org_unit_description", "_org_unit_head_id", b"_org_unit_head_id", "_org_unit_parent_id", b"_org_unit_parent_id", "org_unit_description", b"org_unit_description", "org_unit_head_id", b"org_unit_head_id", "org_unit_parent_id", b"org_unit_parent_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_org_unit_description", b"_org_unit_description", "_org_unit_head_id", b"_org_unit_head_id", "_org_unit_parent_id", b"_org_unit_parent_id", "created_by", b"created_by", "org_unit_code", b"org_unit_code", "org_unit_description", b"org_unit_description", "org_unit_head_id", b"org_unit_head_id", "org_unit_level", b"org_unit_level", "org_unit_metadata", b"org_unit_metadata", "org_unit_name", b"org_unit_name", "org_unit_parent_id", b"org_unit_parent_id", "org_unit_path", b"org_unit_path", "org_unit_type", b"org_unit_type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_description", b"_org_unit_description"]) -> typing.Literal["org_unit_description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_head_id", b"_org_unit_head_id"]) -> typing.Literal["org_unit_head_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_parent_id", b"_org_unit_parent_id"]) -> typing.Literal["org_unit_parent_id"] | None: ...

Global___CreateOrgUnitRequest: typing_extensions.TypeAlias = CreateOrgUnitRequest

@typing.final
class UpdateOrgUnitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class OrgUnitMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_NAME_FIELD_NUMBER: builtins.int
    ORG_UNIT_TYPE_FIELD_NUMBER: builtins.int
    ORG_UNIT_PARENT_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_LEVEL_FIELD_NUMBER: builtins.int
    ORG_UNIT_PATH_FIELD_NUMBER: builtins.int
    ORG_UNIT_HEAD_ID_FIELD_NUMBER: builtins.int
    ORG_UNIT_DESCRIPTION_FIELD_NUMBER: builtins.int
    ORG_UNIT_METADATA_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    UPDATED_BY_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    org_unit_name: builtins.str
    org_unit_type: builtins.str
    org_unit_parent_id: builtins.int
    org_unit_level: builtins.int
    org_unit_path: builtins.str
    org_unit_head_id: builtins.int
    org_unit_description: builtins.str
    is_active: builtins.bool
    updated_by: builtins.int
    @property
    def org_unit_metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
        org_unit_name: builtins.str | None = ...,
        org_unit_type: builtins.str | None = ...,
        org_unit_parent_id: builtins.int | None = ...,
        org_unit_level: builtins.int | None = ...,
        org_unit_path: builtins.str | None = ...,
        org_unit_head_id: builtins.int | None = ...,
        org_unit_description: builtins.str | None = ...,
        org_unit_metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        is_active: builtins.bool | None = ...,
        updated_by: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_is_active", b"_is_active", "_org_unit_description", b"_org_unit_description", "_org_unit_head_id", b"_org_unit_head_id", "_org_unit_level", b"_org_unit_level", "_org_unit_name", b"_org_unit_name", "_org_unit_parent_id", b"_org_unit_parent_id", "_org_unit_path", b"_org_unit_path", "_org_unit_type", b"_org_unit_type", "is_active", b"is_active", "org_unit_description", b"org_unit_description", "org_unit_head_id", b"org_unit_head_id", "org_unit_level", b"org_unit_level", "org_unit_name", b"org_unit_name", "org_unit_parent_id", b"org_unit_parent_id", "org_unit_path", b"org_unit_path", "org_unit_type", b"org_unit_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_is_active", b"_is_active", "_org_unit_description", b"_org_unit_description", "_org_unit_head_id", b"_org_unit_head_id", "_org_unit_level", b"_org_unit_level", "_org_unit_name", b"_org_unit_name", "_org_unit_parent_id", b"_org_unit_parent_id", "_org_unit_path", b"_org_unit_path", "_org_unit_type", b"_org_unit_type", "is_active", b"is_active", "org_unit_description", b"org_unit_description", "org_unit_head_id", b"org_unit_head_id", "org_unit_id", b"org_unit_id", "org_unit_level", b"org_unit_level", "org_unit_metadata", b"org_unit_metadata", "org_unit_name", b"org_unit_name", "org_unit_parent_id", b"org_unit_parent_id", "org_unit_path", b"org_unit_path", "org_unit_type", b"org_unit_type", "updated_by", b"updated_by"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_is_active", b"_is_active"]) -> typing.Literal["is_active"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_description", b"_org_unit_description"]) -> typing.Literal["org_unit_description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_head_id", b"_org_unit_head_id"]) -> typing.Literal["org_unit_head_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_level", b"_org_unit_level"]) -> typing.Literal["org_unit_level"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_name", b"_org_unit_name"]) -> typing.Literal["org_unit_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_parent_id", b"_org_unit_parent_id"]) -> typing.Literal["org_unit_parent_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_path", b"_org_unit_path"]) -> typing.Literal["org_unit_path"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_org_unit_type", b"_org_unit_type"]) -> typing.Literal["org_unit_type"] | None: ...

Global___UpdateOrgUnitRequest: typing_extensions.TypeAlias = UpdateOrgUnitRequest

@typing.final
class DeleteOrgUnitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    SOFT_DELETE_FIELD_NUMBER: builtins.int
    DELETED_BY_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    soft_delete: builtins.bool
    deleted_by: builtins.int
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
        soft_delete: builtins.bool = ...,
        deleted_by: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deleted_by", b"deleted_by", "org_unit_id", b"org_unit_id", "soft_delete", b"soft_delete"]) -> None: ...

Global___DeleteOrgUnitRequest: typing_extensions.TypeAlias = DeleteOrgUnitRequest

@typing.final
class GetOrgUnitChildrenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_PARENT_ID_FIELD_NUMBER: builtins.int
    RECURSIVE_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    org_unit_parent_id: builtins.int
    recursive: builtins.bool
    @property
    def pagination(self) -> proto.common.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        org_unit_parent_id: builtins.int = ...,
        recursive: builtins.bool = ...,
        pagination: proto.common.common_pb2.Pagination | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["org_unit_parent_id", b"org_unit_parent_id", "pagination", b"pagination", "recursive", b"recursive"]) -> None: ...

Global___GetOrgUnitChildrenRequest: typing_extensions.TypeAlias = GetOrgUnitChildrenRequest

@typing.final
class GetOrgUnitHierarchyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOT_ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    MAX_DEPTH_FIELD_NUMBER: builtins.int
    root_org_unit_id: builtins.int
    max_depth: builtins.int
    def __init__(
        self,
        *,
        root_org_unit_id: builtins.int | None = ...,
        max_depth: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_root_org_unit_id", b"_root_org_unit_id", "root_org_unit_id", b"root_org_unit_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_root_org_unit_id", b"_root_org_unit_id", "max_depth", b"max_depth", "root_org_unit_id", b"root_org_unit_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_root_org_unit_id", b"_root_org_unit_id"]) -> typing.Literal["root_org_unit_id"] | None: ...

Global___GetOrgUnitHierarchyRequest: typing_extensions.TypeAlias = GetOrgUnitHierarchyRequest

@typing.final
class GetOrgUnitAncestorsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["org_unit_id", b"org_unit_id"]) -> None: ...

Global___GetOrgUnitAncestorsRequest: typing_extensions.TypeAlias = GetOrgUnitAncestorsRequest

@typing.final
class BatchGetOrgUnitsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_IDS_FIELD_NUMBER: builtins.int
    @property
    def org_unit_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        org_unit_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["org_unit_ids", b"org_unit_ids"]) -> None: ...

Global___BatchGetOrgUnitsRequest: typing_extensions.TypeAlias = BatchGetOrgUnitsRequest

@typing.final
class OrgUnitHierarchy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    @property
    def org_unit(self) -> Global___OrgUnit: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___OrgUnitHierarchy]: ...
    def __init__(
        self,
        *,
        org_unit: Global___OrgUnit | None = ...,
        children: collections.abc.Iterable[Global___OrgUnitHierarchy] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["org_unit", b"org_unit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "org_unit", b"org_unit"]) -> None: ...

Global___OrgUnitHierarchy: typing_extensions.TypeAlias = OrgUnitHierarchy

@typing.final
class GetOrgUnitTypesRequest(google.protobuf.message.Message):
    """Empty request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetOrgUnitTypesRequest: typing_extensions.TypeAlias = GetOrgUnitTypesRequest

@typing.final
class GetOrgUnitTypesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPES_FIELD_NUMBER: builtins.int
    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        types: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["types", b"types"]) -> None: ...

Global___GetOrgUnitTypesResponse: typing_extensions.TypeAlias = GetOrgUnitTypesResponse

@typing.final
class SoftDeleteOrgUnitRequest(google.protobuf.message.Message):
    """Soft delete operations messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    DELETED_BY_USER_ID_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    deleted_by_user_id: builtins.int
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
        deleted_by_user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deleted_by_user_id", b"deleted_by_user_id", "org_unit_id", b"org_unit_id"]) -> None: ...

Global___SoftDeleteOrgUnitRequest: typing_extensions.TypeAlias = SoftDeleteOrgUnitRequest

@typing.final
class RestoreOrgUnitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORG_UNIT_ID_FIELD_NUMBER: builtins.int
    org_unit_id: builtins.int
    def __init__(
        self,
        *,
        org_unit_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["org_unit_id", b"org_unit_id"]) -> None: ...

Global___RestoreOrgUnitRequest: typing_extensions.TypeAlias = RestoreOrgUnitRequest

@typing.final
class ListDeletedOrgUnitsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: builtins.int
    SEARCH_FIELD_NUMBER: builtins.int
    search: builtins.str
    @property
    def pagination(self) -> proto.common.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        pagination: proto.common.common_pb2.Pagination | None = ...,
        search: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_search", b"_search", "pagination", b"pagination", "search", b"search"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_search", b"_search", "pagination", b"pagination", "search", b"search"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_search", b"_search"]) -> typing.Literal["search"] | None: ...

Global___ListDeletedOrgUnitsRequest: typing_extensions.TypeAlias = ListDeletedOrgUnitsRequest
