# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.common import common_pb2 as proto_dot_common_dot_common__pb2
from proto.org_unit import org_unit_pb2 as proto_dot_org__unit_dot_org__unit__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/org_unit/org_unit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrgUnitServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrgUnit = channel.unary_unary(
                '/org_unit.OrgUnitService/GetOrgUnit',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
                _registered_method=True)
        self.GetOrgUnitByCode = channel.unary_unary(
                '/org_unit.OrgUnitService/GetOrgUnitByCode',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitByCodeRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
                _registered_method=True)
        self.ListOrgUnits = channel.unary_unary(
                '/org_unit.OrgUnitService/ListOrgUnits',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
                _registered_method=True)
        self.CreateOrgUnit = channel.unary_unary(
                '/org_unit.OrgUnitService/CreateOrgUnit',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.CreateOrgUnitRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
                _registered_method=True)
        self.UpdateOrgUnit = channel.unary_unary(
                '/org_unit.OrgUnitService/UpdateOrgUnit',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.UpdateOrgUnitRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
                _registered_method=True)
        self.DeleteOrgUnit = channel.unary_unary(
                '/org_unit.OrgUnitService/DeleteOrgUnit',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.DeleteOrgUnitRequest.SerializeToString,
                response_deserializer=proto_dot_common_dot_common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetOrgUnitChildren = channel.unary_unary(
                '/org_unit.OrgUnitService/GetOrgUnitChildren',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitChildrenRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
                _registered_method=True)
        self.GetOrgUnitHierarchy = channel.unary_unary(
                '/org_unit.OrgUnitService/GetOrgUnitHierarchy',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitHierarchyRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnitHierarchy.FromString,
                _registered_method=True)
        self.GetOrgUnitAncestors = channel.unary_unary(
                '/org_unit.OrgUnitService/GetOrgUnitAncestors',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitAncestorsRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
                _registered_method=True)
        self.BatchGetOrgUnits = channel.unary_unary(
                '/org_unit.OrgUnitService/BatchGetOrgUnits',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.BatchGetOrgUnitsRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
                _registered_method=True)
        self.GetOrgUnitTypes = channel.unary_unary(
                '/org_unit.OrgUnitService/GetOrgUnitTypes',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitTypesRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitTypesResponse.FromString,
                _registered_method=True)
        self.SoftDeleteOrgUnit = channel.unary_unary(
                '/org_unit.OrgUnitService/SoftDeleteOrgUnit',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.SoftDeleteOrgUnitRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
                _registered_method=True)
        self.RestoreOrgUnit = channel.unary_unary(
                '/org_unit.OrgUnitService/RestoreOrgUnit',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.RestoreOrgUnitRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
                _registered_method=True)
        self.ListDeletedOrgUnits = channel.unary_unary(
                '/org_unit.OrgUnitService/ListDeletedOrgUnits',
                request_serializer=proto_dot_org__unit_dot_org__unit__pb2.ListDeletedOrgUnitsRequest.SerializeToString,
                response_deserializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
                _registered_method=True)


class OrgUnitServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrgUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrgUnitByCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrgUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrgUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrgUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOrgUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrgUnitChildren(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrgUnitHierarchy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrgUnitAncestors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetOrgUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrgUnitTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SoftDeleteOrgUnit(self, request, context):
        """Soft delete operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreOrgUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeletedOrgUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrgUnitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrgUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrgUnit,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.SerializeToString,
            ),
            'GetOrgUnitByCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrgUnitByCode,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitByCodeRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.SerializeToString,
            ),
            'ListOrgUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrgUnits,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.SerializeToString,
            ),
            'CreateOrgUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrgUnit,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.CreateOrgUnitRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.SerializeToString,
            ),
            'UpdateOrgUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrgUnit,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.UpdateOrgUnitRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.SerializeToString,
            ),
            'DeleteOrgUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOrgUnit,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.DeleteOrgUnitRequest.FromString,
                    response_serializer=proto_dot_common_dot_common__pb2.StatusResponse.SerializeToString,
            ),
            'GetOrgUnitChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrgUnitChildren,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitChildrenRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.SerializeToString,
            ),
            'GetOrgUnitHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrgUnitHierarchy,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitHierarchyRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnitHierarchy.SerializeToString,
            ),
            'GetOrgUnitAncestors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrgUnitAncestors,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitAncestorsRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.SerializeToString,
            ),
            'BatchGetOrgUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetOrgUnits,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.BatchGetOrgUnitsRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.SerializeToString,
            ),
            'GetOrgUnitTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrgUnitTypes,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitTypesRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitTypesResponse.SerializeToString,
            ),
            'SoftDeleteOrgUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.SoftDeleteOrgUnit,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.SoftDeleteOrgUnitRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.SerializeToString,
            ),
            'RestoreOrgUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreOrgUnit,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.RestoreOrgUnitRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.SerializeToString,
            ),
            'ListDeletedOrgUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeletedOrgUnits,
                    request_deserializer=proto_dot_org__unit_dot_org__unit__pb2.ListDeletedOrgUnitsRequest.FromString,
                    response_serializer=proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org_unit.OrgUnitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org_unit.OrgUnitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrgUnitService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrgUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/GetOrgUnit',
            proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrgUnitByCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/GetOrgUnitByCode',
            proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitByCodeRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrgUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/ListOrgUnits',
            proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrgUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/CreateOrgUnit',
            proto_dot_org__unit_dot_org__unit__pb2.CreateOrgUnitRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrgUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/UpdateOrgUnit',
            proto_dot_org__unit_dot_org__unit__pb2.UpdateOrgUnitRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOrgUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/DeleteOrgUnit',
            proto_dot_org__unit_dot_org__unit__pb2.DeleteOrgUnitRequest.SerializeToString,
            proto_dot_common_dot_common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrgUnitChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/GetOrgUnitChildren',
            proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitChildrenRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrgUnitHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/GetOrgUnitHierarchy',
            proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitHierarchyRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.OrgUnitHierarchy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrgUnitAncestors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/GetOrgUnitAncestors',
            proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitAncestorsRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetOrgUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/BatchGetOrgUnits',
            proto_dot_org__unit_dot_org__unit__pb2.BatchGetOrgUnitsRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrgUnitTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/GetOrgUnitTypes',
            proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitTypesRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.GetOrgUnitTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SoftDeleteOrgUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/SoftDeleteOrgUnit',
            proto_dot_org__unit_dot_org__unit__pb2.SoftDeleteOrgUnitRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreOrgUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/RestoreOrgUnit',
            proto_dot_org__unit_dot_org__unit__pb2.RestoreOrgUnitRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.OrgUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeletedOrgUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org_unit.OrgUnitService/ListDeletedOrgUnits',
            proto_dot_org__unit_dot_org__unit__pb2.ListDeletedOrgUnitsRequest.SerializeToString,
            proto_dot_org__unit_dot_org__unit__pb2.ListOrgUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
